services:
  - name: flask-gps-tracker
    type: web
    env: python
    region: oregon  # Choose a region (Oregon, Frankfurt, etc.)
    plan: free  # Use the free tier
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
